mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from pdf import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('pdf.urls')),
]

mysite/pdf/urls.py
from django.urls import path
from . import views

app_name = 'pdf'

urlpatterns = [
    path('',views.CreateProfile.as_view(),name='create_profile'),
    path('<int:pk>/',views.ProfileDetailView.as_view(),name='profile_detail'),
    path('<int:pk>/download/',views.create_pdf,name='download'),
]

mysite/pdf/models.py
from django.db import models
from django.urls import reverse

# Create your models here.


class Profile(models.Model):

    name = models.CharField(max_length=200)
    email = models.CharField(max_length=200)
    phone = models.CharField(max_length=200)
    summary = models.TextField(max_length=2000)
    degree = models.CharField(max_length=200)
    school = models.CharField(max_length=200)
    university = models.CharField(max_length=200)
    previous_work = models.TextField(max_length=1000)
    skills = models.TextField(max_length=1000)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('pdf:profile_detail',kwargs={'pk':self.pk})

mysite/pdf/forms.py
from django import forms
from .models import Profile

class ProfileForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = ('name','email','phone','summary','degree','school','university','previous_work','skills')

mysite/pdf/views.py
from django.shortcuts import render
from django.views.generic import CreateView,DetailView
from .models import Profile
from .forms import ProfileForm

import pdfkit

# config = pdfkit.configuration(wkhtmltopdf='C:\\Program Files\\wkhtmltopdf\\bin')
# pdfkit.from_url(configuration=config)

from django.http import HttpResponse
from django.template import loader

# Create your views here.


class CreateProfile(CreateView):
    model = Profile
    form_class = ProfileForm
    template_name = 'pdf/profile_form.html'

class ProfileDetailView(DetailView):
    model = Profile
    template_name = 'pdf/profile_detail.html'
    context_object_name = 'user_cv'



def create_pdf(request,pk):

    user_cv = Profile.objects.get(pk=pk)
    template = loader.get_template('pdf/profile_detail.html')
    html = template.render({'user_cv':user_cv})
    options = {
                'page-size':'Letter',
                'encoding':'UTF-8',
                }
    pdf = pdfkit.from_string(html,False,options)
    response = HttpResponse(pdf,content_type="application/pdf")
    response['Content-Disposition'] = 'attachment'
    filename = "resume.pdf"
    return response





#




#
# import pdfkit
# from django.http import HttpResponse
# from django.template import loader
#
# def create_pdf(request):
#     html = loader.render_to_string('invoice.html', {})
#     output= pdfkit.from_string(html, output_path=False)
#     response = HttpResponse(content_type="application/pdf")
#     response.write(output)
#     return response

mysite/pdf/templates/pdf/profile_detail.html
{% extends 'base.html' %}

{% block body%}
<div class="container">

    <h2>Name: {{user_cv.name}}</h2>
    <h2>Mail: {{user_cv.email}}</h2>
    <h2>Phone: {{user_cv.phone}}</h2>
    <hr>
    <br>
    <p>Summary</p>
    <p> {{user_cv.summary}}</p>
    <hr>
    <p>Skills</p>
    <p> {{user_cv.skills}}</p>
    <hr>
    <p>Education</p>
    <ul>
      <li>Schooling: {{user_cv.university}}</li>
      <li>{{user_cv.degree}} from {{user_cv.school}}</li>
    </ul>
    <hr>
    <p>previous Work</p>
    <p> {{user_cv.previous_work}}</p>
    <hr>
    <br>
    <a href="{% url 'pdf:download' pk=user_cv.pk %}" class="btn btn-warning">Download</a>
</div>
{% endblock %}

mysite/pdf/templates/pdf/profile_form.html
{% extends 'base.html' %}
{% load bootstrap3 %}


{% block body %}

<div class="container">
  <div class="row">

    <form method="POST">
      {% csrf_token %}
      {% bootstrap_form form %}

      <input type="submit" class="btn btn-warning btn-large" value="Create">
    </form>

  </div>
</div>

{% endblock %}

mysite/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>CV_Builder</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  </head>
  <body>

    <nav class="navbar navbar-dark bg-dark">
      <div class="container">
      <a href="{% url 'pdf:create_profile' %}" class="navbar-brand">CV BUILDER</a>
        <div class="navbar">

          <a href="https://github.com/SH-Ali-Sheikhi" class="nav-item nav-link">Github</a>
          <a href="https://stackoverflow.com/users/15071015/ali-sheikhi?tab=profile" class="nav-item nav-link">Stackoverflow</a>
          <a href="https://www.linkedin.com/in/ali-sheikhi-28a527208/" class="nav-item nav-link">LinkedIn</a>


        </div>
      </div>
    </nav>


    <br>
    {% block body %}
    {% endblock %}

  </body>
</html>